Repository UBCFormulaElectric/Consolidated-Firmware, pull requests merged in 2024-12, with the labels that each got.

#1401 Ninja Generator Presets for CMake
  CMakePresets.json
Labels: Build System/DevEx

#1365 USB Middleware
  firmware/cmake/bootlib.cmake
  firmware/cmake/stmlib.cmake
  firmware/dev/f4dev/CMakeLists.txt
  firmware/dev/f4dev/src/cubemx/Inc/stm32f4xx_hal_conf.h
  firmware/dev/f4dev/src/cubemx/Inc/stm32f4xx_it.h
  firmware/dev/f4dev/src/cubemx/Inc/usb_device.h
  firmware/dev/f4dev/src/cubemx/Inc/usbd_cdc_if.h
  firmware/dev/f4dev/src/cubemx/Inc/usbd_conf.h
  firmware/dev/f4dev/src/cubemx/Inc/usbd_desc.h
  firmware/dev/f4dev/src/cubemx/Src/main.c
  firmware/dev/f4dev/src/cubemx/Src/stm32f4xx_it.c
  firmware/dev/f4dev/src/cubemx/Src/usb_device.c
  firmware/dev/f4dev/src/cubemx/Src/usbd_cdc_if.c
  firmware/dev/f4dev/src/cubemx/Src/usbd_conf.c
  firmware/dev/f4dev/src/cubemx/Src/usbd_desc.c
  firmware/dev/f4dev/src/cubemx/f4dev.ioc
  firmware/dev/f4dev/src/cubemx/f4dev.ioc.md5
  firmware/dev/h7dev/CMakeLists.txt
  firmware/dev/h7dev/src/cubemx/Inc/stm32h7xx_hal_conf.h
  firmware/dev/h7dev/src/cubemx/Inc/stm32h7xx_it.h
  firmware/dev/h7dev/src/cubemx/Inc/usb_device.h
  firmware/dev/h7dev/src/cubemx/Inc/usbd_cdc_if.h
  firmware/dev/h7dev/src/cubemx/Inc/usbd_conf.h
  firmware/dev/h7dev/src/cubemx/Inc/usbd_desc.h
  firmware/dev/h7dev/src/cubemx/Src/main.c
  firmware/dev/h7dev/src/cubemx/Src/stm32h7xx_hal_msp.c
  firmware/dev/h7dev/src/cubemx/Src/stm32h7xx_it.c
  firmware/dev/h7dev/src/cubemx/Src/usb_device.c
  firmware/dev/h7dev/src/cubemx/Src/usbd_cdc_if.c
  firmware/dev/h7dev/src/cubemx/Src/usbd_conf.c
  firmware/dev/h7dev/src/cubemx/Src/usbd_desc.c
  firmware/dev/h7dev/src/cubemx/h7dev.ioc
  firmware/dev/h7dev/src/cubemx/h7dev.ioc.md5
  firmware/quadruna/BMS/CMakeLists.txt
  firmware/quadruna/CRIT/CMakeLists.txt
  firmware/quadruna/FSM/CMakeLists.txt
  firmware/quadruna/RSM/CMakeLists.txt
  firmware/quadruna/VC/CMakeLists.txt
  firmware/quintuna/CRIT/CMakeLists.txt
  firmware/quintuna/RSM/CMakeLists.txt
  firmware/quintuna/VC/CMakeLists.txt
  firmware/shared/src/app/app_utils.h
Labels: Drivers, Validation

#1387 Current Sensor Calibration
  firmware/quadruna/BMS/src/app/app_tractiveSystem.h
  firmware/quadruna/BMS/src/io/io_tractiveSystem.c
Labels: BMS

#1325 Heartbeat Refactor
  firmware/cmake/shared.cmake
  firmware/cmake/tests.cmake
  firmware/logfs/CMakeLists.txt
  firmware/quadruna/BMS/CMakeLists.txt
  firmware/quadruna/BMS/src/app/app_globals.h
  firmware/quadruna/BMS/src/app/app_heartbeatMonitors.c
  firmware/quadruna/BMS/src/app/app_heartbeatMonitors.h
  firmware/quadruna/BMS/src/app/states/app_allStates.c
  firmware/quadruna/BMS/src/app/states/app_initState.c
  firmware/quadruna/BMS/src/tasks.c
  firmware/quadruna/BMS/test/test_bmsBaseStateMachineTest.h
  firmware/quadruna/BMS/test/test_faults.cpp
  firmware/quadruna/BMS/test/test_imd.h
  firmware/quadruna/BMS/test/test_stateMachine.cpp
  firmware/quadruna/CRIT/CMakeLists.txt
  firmware/quadruna/CRIT/src/app/app_heartbeatMonitors.c
  firmware/quadruna/CRIT/src/app/app_heartbeatMonitors.h
  firmware/quadruna/CRIT/src/app/app_mainState.c
  firmware/quadruna/CRIT/src/tasks.c
  firmware/quadruna/CRIT/test/test_critBaseStateMachineTest.h
  firmware/quadruna/RSM/CMakeLists.txt
  firmware/quadruna/RSM/src/app/app_heartbeatMonitors.c
  firmware/quadruna/RSM/src/app/app_heartbeatMonitors.h
  firmware/quadruna/RSM/src/app/app_mainState.c
  firmware/quadruna/RSM/src/tasks.c
  firmware/quadruna/RSM/test/test_faults.cpp
  firmware/quadruna/RSM/test/test_rsmBaseStateMachineTest.h
  firmware/quadruna/VC/CMakeLists.txt
  firmware/quadruna/VC/src/app/app_heartbeatMonitors.c
  firmware/quadruna/VC/src/app/app_heartbeatMonitors.h
  firmware/quadruna/VC/src/app/states/app_allStates.c
  firmware/quadruna/VC/src/tasks.c
  firmware/quadruna/VC/test/test_stateMachine.cpp
  firmware/quadruna/VC/test/test_vcBaseStateMachineTest.h
  firmware/shared/CMakeLists.txt
  firmware/shared/src/app/app_heartbeatBoard.c
  firmware/shared/src/app/app_heartbeatBoard.h
  firmware/shared/src/app/app_heartbeatMonitor.c
  firmware/shared/src/app/app_heartbeatMonitor.h
  firmware/shared/test/app_heartbeatBoardsEnum.h
  firmware/shared/test/test_heartbeatMonitor.cpp
Labels: Build System/DevEx

#1395 Quintuna CRIT Bringup
  firmware/quintuna/CRIT/boot/cubemx/Inc/FreeRTOSConfig.h
  firmware/quintuna/CRIT/boot/cubemx/Inc/main.h
  firmware/quintuna/CRIT/boot/cubemx/Inc/stm32f4xx_it.h
  firmware/quintuna/CRIT/boot/cubemx/Src/freertos.c
  firmware/quintuna/CRIT/boot/cubemx/Src/main.c
  firmware/quintuna/CRIT/boot/cubemx/Src/stm32f4xx_hal_msp.c
  firmware/quintuna/CRIT/boot/cubemx/Src/stm32f4xx_hal_timebase_tim.c
  firmware/quintuna/CRIT/boot/cubemx/Src/stm32f4xx_it.c
  firmware/quintuna/CRIT/boot/cubemx/Src/syscalls.c
Labels: DIM [OS]
