Repository UBCFormulaElectric/Consolidated-Firmware, pull requests merged in 2024-03, with the labels that each got.

#1173 move chimera, setup scope
  Pipfile
  firmware/chimera/chimera/__init__.py
  firmware/chimera/generate_libs.sh
  firmware/chimera/setup.py
  validationtools/pyproject.toml
  validationtools/validationtools/__init__.py
  validationtools/validationtools/chimera/README.txt
  validationtools/validationtools/chimera/__init__.py
  validationtools/validationtools/chimera/chimera.py
  validationtools/validationtools/chimera/example/__init__.py
  validationtools/validationtools/chimera/example/test_bms.py
  validationtools/validationtools/chimera/example/test_crit.py
  validationtools/validationtools/chimera/example/test_fsm.py
  validationtools/validationtools/chimera/example/test_rsm.py
  validationtools/validationtools/chimera/example/test_vc.py
  validationtools/validationtools/chimera/generate_libs.ps1
  validationtools/validationtools/chimera/generate_libs.sh
  validationtools/validationtools/chimera/proto_libs/BMS_pb2.py
  validationtools/validationtools/chimera/proto_libs/CRIT_pb2.py
  validationtools/validationtools/chimera/proto_libs/FSM_pb2.py
  validationtools/validationtools/chimera/proto_libs/RSM_pb2.py
  validationtools/validationtools/chimera/proto_libs/VC_pb2.py
  validationtools/validationtools/chimera/proto_libs/__init__.py
  validationtools/validationtools/chimera/proto_libs/shared_pb2.py
  validationtools/validationtools/scope/.gitignore
  validationtools/validationtools/scope/README.md
  validationtools/validationtools/scope/__init__.py
  validationtools/validationtools/scope/_scope.py
  validationtools/validationtools/scope/template.py
Labels: Build System/DevEx

#1172 Dikshit/open wire check v2
  firmware/quadruna/BMS/src/app/app_accumulator.c
  firmware/quadruna/BMS/src/app/app_accumulator.h
  firmware/quadruna/BMS/src/app/states/app_allStates.c
  firmware/quadruna/BMS/src/app/states/app_initState.c
  firmware/thruna/BMS/src/app/app_accumulator.c
  firmware/thruna/BMS/src/app/app_accumulator.h
  firmware/thruna/BMS/src/app/states/app_allStates.c
  firmware/thruna/BMS/src/app/states/app_initState.c
Labels: BMS

#1160 Quadruna Heartbeat Monitor, and Car Specific Shared Directories
  .vscode/settings.json
  firmware/quadruna/BMS/CMakeLists.txt
  firmware/quadruna/BMS/src/tasks.c
  firmware/quadruna/BMS/test/test_bmsBaseStateMachineTest.h
  firmware/quadruna/CMakeLists.txt
  firmware/quadruna/CRIT/CMakeLists.txt
  firmware/quadruna/FSM/CMakeLists.txt
  firmware/quadruna/FSM/test/test_fsmBaseStateMachineTest.h
  firmware/quadruna/RSM/CMakeLists.txt
  firmware/quadruna/VC/CMakeLists.txt
  firmware/quadruna/VC/test/test_vcBaseStateMachineTest.h
  firmware/quadruna/shared/src/app/app_heartbeatBoardsEnum.h
  firmware/shared/src/app/app_heartbeatMonitor.c
  firmware/shared/src/app/app_heartbeatMonitor.h
  firmware/shared/test/app_heartbeatBoardsEnum.h
  firmware/shared/test/test_heartbeatMonitor.cpp
  firmware/thruna/BMS/CMakeLists.txt
  firmware/thruna/BMS/src/tasks.c
  firmware/thruna/BMS/test/test_bmsBaseStateMachineTest.h
  firmware/thruna/CMakeLists.txt
  firmware/thruna/DCM/CMakeLists.txt
  firmware/thruna/DCM/src/tasks.c
  firmware/thruna/DCM/test/test_dcmBaseStateMachineTest.h
  firmware/thruna/DIM/CMakeLists.txt
  firmware/thruna/DIM/src/tasks.c
  firmware/thruna/DIM/test/test_dimBaseStateMachineTest.h
  firmware/thruna/FSM/CMakeLists.txt
  firmware/thruna/FSM/src/tasks.c
  firmware/thruna/FSM/test/test_fsmBaseStateMachineTest.h
  firmware/thruna/PDM/CMakeLists.txt
  firmware/thruna/PDM/src/tasks.c
  firmware/thruna/PDM/test/test_pdmBaseStateMachineTest.h
  firmware/thruna/shared/src/app/app_heartbeatBoardsEnum.h
Labels: Drivers

#1094 Jpatch/modify signals
  software/tracksight/backend/app/process/AST.py
  software/tracksight/backend/app/process/interpreter.py
  software/tracksight/backend/app/process/lexer.py
  software/tracksight/backend/app/process/parse_expression.py
  software/tracksight/backend/app/process/parser.py
  software/tracksight/backend/app/tests/process_tests/__init__.py
  software/tracksight/backend/app/tests/process_tests/parse_expression_test.py
  software/tracksight/backend/app/tests/process_tests/test_expression_evaluation.py
  software/tracksight/backend/dbcs/canMsgs.dbc
  software/tracksight/backend/mock_data/customSignals/README.md
  software/tracksight/backend/util_scripts/parse_MF4_files.py
  software/tracksight/frontend/src/app/components/editSignals.tsx
Labels: Telemetry

#1159 Vehicle Dynamics Testing Changes
  firmware/shared/src/app/app_units.h
  firmware/shared/src/app/app_utils.h
  firmware/thruna/DCM/src/app/vehicle_dynamics/app_regen.c
  firmware/thruna/DCM/src/app/vehicle_dynamics/app_regen.h
  firmware/thruna/DCM/src/app/vehicle_dynamics/app_torqueVectoring.c
  firmware/thruna/DCM/src/app/vehicle_dynamics/app_tractionControl.c
  firmware/thruna/DCM/src/app/vehicle_dynamics/app_tractionControl.h
  firmware/thruna/DCM/src/app/vehicle_dynamics/app_vehicleDynamics.h
  firmware/thruna/DCM/src/app/vehicle_dynamics/app_vehicleDynamicsConstants.c
  firmware/thruna/DCM/src/app/vehicle_dynamics/app_vehicleDynamicsConstants.h
  firmware/thruna/DCM/test/vehicle_dynamics/test_regen.cpp
  firmware/thruna/DCM/test/vehicle_dynamics/test_tractionControl.cpp
  firmware/thruna/PDM/src/app/states/app_initState.c
Labels: Torque Vectoring, VC

#1181 Quadruna BMS SPI Segment Module Communication
  firmware/quadruna/BMS/src/app/states/app_allStates.c
  firmware/quadruna/BMS/src/cubemx/BMS.ioc
  firmware/quadruna/BMS/src/cubemx/BMS.ioc.md5
  firmware/quadruna/BMS/src/cubemx/Src/main.c
  firmware/quadruna/BMS/src/cubemx/Src/stm32h7xx_hal_msp.c
  firmware/quadruna/BMS/src/io/ltc6813/io_ltc6813CellTemps.c
  firmware/quadruna/BMS/src/io/ltc6813/io_ltc6813CellVoltages.c
  firmware/quadruna/BMS/src/io/ltc6813/io_ltc6813Shared.c
  firmware/quadruna/BMS/src/io/ltc6813/io_ltc6813Shared.h
  firmware/shared/src/hw/hw_spi.c
  firmware/shared/src/hw/hw_spi.h
  firmware/thruna/BMS/src/io/ltc6813/io_ltc6813CellTemps.c
  firmware/thruna/BMS/src/io/ltc6813/io_ltc6813CellVoltages.c
  firmware/thruna/BMS/src/io/ltc6813/io_ltc6813Shared.c
Labels: BMS, Drivers

#1141 Critdim
  .vscode/launch.json
  can_bus/quadruna/CRIT/CRIT_alerts.json
  can_bus/quadruna/CRIT/CRIT_enum.json
  can_bus/quadruna/CRIT/CRIT_rx.json
  can_bus/quadruna/CRIT/CRIT_tx.json
  firmware/quadruna/CMakeLists.txt
  firmware/quadruna/CRIT/CMakeLists.txt
  firmware/quadruna/CRIT/src/app/app_globals.c
  firmware/quadruna/CRIT/src/app/app_globals.h
  firmware/quadruna/CRIT/src/app/app_mainState.c
  firmware/quadruna/CRIT/src/app/app_mainState.h
  firmware/quadruna/CRIT/src/cubemx/Inc/FreeRTOSConfig.h
  firmware/quadruna/CRIT/src/hw/hw_stackWaterMarkConfig.c
  firmware/quadruna/CRIT/src/hw/hw_stackWaterMarkConfig.h
  firmware/quadruna/CRIT/src/hw/hw_watchdogConfig.c
  firmware/quadruna/CRIT/src/hw/hw_watchdogConfig.h
  firmware/quadruna/CRIT/src/io/io_driveMode.c
  firmware/quadruna/CRIT/src/io/io_driveMode.h
  firmware/quadruna/CRIT/src/tasks.c
Labels: DIM

#1195 VC cmake change and proto autogenerated files set up
  firmware/dev/h7dev/CMakeLists.txt
  firmware/dev/h7dev/cubemx/Inc/stm32h7xx_hal_conf.h
  firmware/dev/h7dev/cubemx/Inc/stm32h7xx_it.h
  firmware/dev/h7dev/cubemx/Src/main.c
  firmware/dev/h7dev/cubemx/Src/stm32h7xx_hal_msp.c
  firmware/dev/h7dev/cubemx/Src/stm32h7xx_it.c
  firmware/dev/h7dev/cubemx/h7dev.ioc
  firmware/dev/h7dev/cubemx/h7dev.ioc.md5
  firmware/dev/h7dev/sample.proto
  firmware/quadruna/VC/proto/telem.proto
  software/hardware_tests/README.md
  software/hardware_tests/proto_test_rx.py
  software/hardware_tests/requirement.txt
  software/hardware_tests/sample.proto
  software/hardware_tests/sample_pb2.py
  software/tracksight/backend/generate_libs.ps1
  software/tracksight/backend/generate_libs.sh
  software/tracksight/backend/util_scripts/telem_pb2.py
Labels: Telemetry, VC

#1192 Chimera Startup Button Implementation
  firmware/quadruna/BMS/src/cubemx/BMS.ioc
  firmware/quadruna/BMS/src/cubemx/BMS.ioc.md5
  firmware/quadruna/BMS/src/cubemx/Src/main.c
  firmware/quadruna/BMS/src/tasks.c
  firmware/quadruna/CRIT/src/tasks.c
  firmware/quadruna/FSM/src/tasks.c
  firmware/quadruna/RSM/src/tasks.c
  firmware/quadruna/VC/src/cubemx/Src/main.c
  firmware/quadruna/VC/src/cubemx/VC.ioc
  firmware/quadruna/VC/src/cubemx/VC.ioc.md5
  firmware/quadruna/VC/src/tasks.c
  firmware/shared/src/io/io_chimera.c
  firmware/shared/src/io/io_chimera.h
Labels: Systems

#1188 Port Thruna PDM to VC
  can_bus/quadruna/INVL/INVL_alerts.json
  can_bus/quadruna/INVL/INVL_enum.json
  can_bus/quadruna/INVL/INVL_rx.json
  can_bus/quadruna/INVL/INVL_tx.json
  can_bus/quadruna/INVR/INVR_alerts.json
  can_bus/quadruna/INVR/INVR_enum.json
  can_bus/quadruna/INVR/INVR_rx.json
  can_bus/quadruna/INVR/INVR_tx.json
  can_bus/quadruna/VC/VC_alerts.json
  can_bus/quadruna/VC/VC_enum.json
  can_bus/quadruna/VC/VC_rx.json
  can_bus/quadruna/VC/VC_tx.json
  firmware/quadruna/VC/CMakeLists.txt
  firmware/quadruna/VC/src/app/app_currentSensing.c
  firmware/quadruna/VC/src/app/app_currentSensing.h
  firmware/quadruna/VC/src/app/app_efuse.c
  firmware/quadruna/VC/src/app/app_efuse.h
  firmware/quadruna/VC/src/app/app_lowVoltageBattery.c
  firmware/quadruna/VC/src/app/app_lowVoltageBattery.h
  firmware/quadruna/VC/src/app/app_powerManager.c
  firmware/quadruna/VC/src/app/app_powerManager.h
  firmware/quadruna/VC/src/app/app_shutdown.c
  firmware/quadruna/VC/src/app/app_shutdown.h
  firmware/quadruna/VC/src/app/states/app_allStates.c
  firmware/quadruna/VC/src/app/states/app_driveState.c
  firmware/quadruna/VC/src/app/states/app_initState.c
  firmware/quadruna/VC/src/app/states/app_inverterOnState.c
  firmware/quadruna/VC/src/app/states/app_inverterOnState.h
  firmware/quadruna/VC/src/hw/hw_adc.c
  firmware/quadruna/VC/src/hw/hw_adc.h
  firmware/quadruna/VC/src/hw/hw_stackWaterMarkConfig.c
  firmware/quadruna/VC/src/io/io_currentSensing.c
  firmware/quadruna/VC/src/io/io_currentSensing.h
  firmware/quadruna/VC/src/io/io_efuse.c
  firmware/quadruna/VC/src/io/io_efuse.h
  firmware/quadruna/VC/src/io/io_lowVoltageBattery.c
  firmware/quadruna/VC/src/io/io_lowVoltageBattery.h
  firmware/quadruna/VC/src/io/io_shutdown.c
  firmware/quadruna/VC/src/io/io_shutdown.h
  firmware/quadruna/VC/src/tasks.c
  firmware/quadruna/VC/test/test_stateMachine.cpp
  firmware/quadruna/VC/test/test_temp.cpp
  firmware/quadruna/VC/test/test_vcBaseStateMachineTest.h
Labels: PDM, VC

#1197 Add load cells, and invoke io_wheels_inputCaptureCallback in Quadruna FSM
  can_bus/quadruna/FSM/FSM_alerts.json
  can_bus/quadruna/FSM/FSM_tx.json
  firmware/quadruna/FSM/CMakeLists.txt
  firmware/quadruna/FSM/src/app/app_loadCell.c
  firmware/quadruna/FSM/src/app/app_loadCell.h
  firmware/quadruna/FSM/src/app/app_mainState.c
  firmware/quadruna/FSM/src/cubemx/Src/main.c
  firmware/quadruna/FSM/src/io/io_loadCell.c
  firmware/quadruna/FSM/src/io/io_loadCell.h
  firmware/quadruna/FSM/src/tasks.c
  firmware/quadruna/FSM/src/tasks.h
  firmware/quadruna/FSM/test/test_canMsgs.cpp
  firmware/quadruna/FSM/test/test_faults.cpp
  firmware/quadruna/FSM/test/test_fsmBaseStateMachineTest.h
Labels: FSM/RSM

#1179 Quadruna RSM Setup
  can_bus/quadruna/RSM/RSM_alerts.json
  can_bus/quadruna/RSM/RSM_enum.json
  can_bus/quadruna/RSM/RSM_rx.json
  can_bus/quadruna/RSM/RSM_tx.json
  firmware/quadruna/RSM/CMakeLists.txt
  firmware/quadruna/RSM/src/app/app_coolant.c
  firmware/quadruna/RSM/src/app/app_coolant.h
  firmware/quadruna/RSM/src/app/app_globals.c
  firmware/quadruna/RSM/src/app/app_globals.h
  firmware/quadruna/RSM/src/app/app_loadCell.c
  firmware/quadruna/RSM/src/app/app_loadCell.h
  firmware/quadruna/RSM/src/app/app_mainState.c
  firmware/quadruna/RSM/src/app/app_mainState.h
  firmware/quadruna/RSM/src/app/app_suspension.c
  firmware/quadruna/RSM/src/app/app_suspension.h
  firmware/quadruna/RSM/src/cubemx/Inc/FreeRTOSConfig.h
  firmware/quadruna/RSM/src/hw/hw_stackWaterMarkConfig.c
  firmware/quadruna/RSM/src/hw/hw_stackWaterMarkConfig.h
  firmware/quadruna/RSM/src/io/io_coolant.c
  firmware/quadruna/RSM/src/io/io_coolant.h
  firmware/quadruna/RSM/src/io/io_loadCell.c
  firmware/quadruna/RSM/src/io/io_loadCell.h
  firmware/quadruna/RSM/src/io/io_suspension.c
  firmware/quadruna/RSM/src/io/io_suspension.h
  firmware/quadruna/RSM/src/tasks.c
  firmware/quadruna/RSM/test/test_coolant.cpp
  firmware/quadruna/RSM/test/test_rsmBaseStateMachine.h
Labels: FSM/RSM

#1191 HW_I2C Drivers
  firmware/quadruna/VC/CMakeLists.txt
  firmware/quadruna/VC/src/cubemx/Src/main.c
  firmware/quadruna/VC/src/cubemx/Src/stm32h7xx_hal_msp.c
  firmware/quadruna/VC/src/cubemx/VC.ioc
  firmware/quadruna/VC/src/cubemx/VC.ioc.md5
  firmware/quadruna/VC/src/io/io_i2c_potentiometer.c
  firmware/quadruna/VC/src/io/io_i2c_potentiometer.h
  firmware/shared/src/hw/hw_i2c.c
  firmware/shared/src/hw/hw_i2c.h
  firmware/shared/src/hw/hw_spi.h
Labels: Drivers

#1208 JLink GDB Server
  .gdbinit
  .gitignore
  .idea/runConfigurations/Quadruna_BMS.xml
  .idea/runConfigurations/Quadruna_CRIT.xml
  .idea/runConfigurations/Quadruna_FSM.xml
  .idea/runConfigurations/Quadruna_RSM.xml
  .idea/runConfigurations/Quadruna_VC.xml
  .idea/runConfigurations/quadruna_BMS_hex.xml
  .idea/runConfigurations/quadruna_CRIT_hex.xml
  .idea/runConfigurations/quadruna_FSM_hex.xml
  .idea/runConfigurations/quadruna_RSM_hex.xml
  .idea/runConfigurations/quadruna_VC_hex.xml
  can_bus/PcanProject.peproj
  can_bus/quadruna/RSM/RSM_alerts.json
  firmware/quadruna/BMS/src/tasks.c
  firmware/quadruna/CRIT/src/app/app_mainState.c
  firmware/quadruna/CRIT/src/tasks.c
  firmware/quadruna/FSM/src/tasks.c
  firmware/quadruna/RSM/src/tasks.c
  firmware/quadruna/VC/src/tasks.c
  firmware/shared/src/hw/hw_can.c
  firmware/shared/src/io/io_can.c
  firmware/shared/src/io/io_can.h
Labels: Build System/DevEx

#1207 IMU Linear Acceleration
  README.md
  can_bus/quadruna/VC/VC_alerts.json
  can_bus/quadruna/VC/VC_tx.json
  firmware/quadruna/VC/CMakeLists.txt
  firmware/quadruna/VC/src/app/states/app_allStates.c
  firmware/quadruna/VC/src/cubemx/Src/main.c
  firmware/quadruna/VC/src/cubemx/Src/stm32h7xx_hal_msp.c
  firmware/quadruna/VC/src/cubemx/VC.ioc
  firmware/quadruna/VC/src/cubemx/VC.ioc.md5
  firmware/quadruna/VC/src/io/io_imu.c
  firmware/quadruna/VC/src/io/io_imu.h
  firmware/quadruna/VC/src/tasks.c
  firmware/shared/src/hw/hw_i2c.c
  firmware/shared/src/hw/hw_i2c.h
Labels: VC

#1132 New JSON files
  can_bus/quadruna/BMS/BMS_alerts.json
  can_bus/quadruna/CRIT/CRIT_alerts.json
  can_bus/quadruna/FSM/FSM_alerts.json
  can_bus/quadruna/RSM/RSM_alerts.json
  can_bus/quadruna/VC/VC_alerts.json
  can_bus/quadruna/dimos/dimos_alerts.json
  can_bus/thruna/BMS/BMS_alerts.json
  can_bus/thruna/DCM/DCM_alerts.json
  can_bus/thruna/DIM/DIM_alerts.json
  can_bus/thruna/FSM/FSM_alerts.json
  can_bus/thruna/PDM/PDM_alerts.json
  firmware/thruna/BMS/Test/Src/Test_Faults.cpp
  scripts/code_generation/jsoncan/example_generated/app/app_canAlerts.c
  scripts/code_generation/jsoncan/example_generated/app/app_canAlerts.h
  scripts/code_generation/jsoncan/example_json/FSM/FSM_alerts.json
  scripts/code_generation/jsoncan/example_json/JCT/JCT_alerts.json
  scripts/code_generation/jsoncan/src/can_database.py
  scripts/code_generation/jsoncan/src/codegen/c_generation/app_can_alerts_module.py
  scripts/code_generation/jsoncan/src/codegen/c_generation/c_config.py
  scripts/code_generation/jsoncan/src/codegen/c_generation/c_writer.py
  scripts/code_generation/jsoncan/src/json_parsing/json_can_parsing.py
  scripts/code_generation/jsoncan/src/json_parsing/schema_validation.py
Labels: CAN
