Repository UBCFormulaElectric/Consolidated-Firmware, pull requests merged in 2024-11, with the labels that each got.

#1359 `JLinkGDBServerCLExe` -> `JLinkGDBServer` on MacOS to enable Brew Installs
  .vscode/launch.json
Labels: Build System/DevEx

#1373 C++ StackWatermark
  can_bus/quintuna/CRIT/CRIT_tx.json
  firmware/quintuna/CRIT/CMakeLists.txt
  firmware/quintuna/CRIT/src/app/app_mainState.cpp
  firmware/quintuna/CRIT/src/app/app_stackMonitorConfig.cpp
  firmware/quintuna/CRIT/src/app/app_stackMonitorConfig.h
  firmware/quintuna/CRIT/src/cubemx/Inc/main.h
  firmware/quintuna/CRIT/src/io/io_stackMonitorConfig.h
  firmware/quintuna/CRIT/src/tasks.cpp
  firmware/shared/srcpp/app/app_stackMonitor.h
  firmware/shared/srcpp/io/io_stackMonitor.cpp
  firmware/shared/srcpp/io/io_stackMonitor.h
Labels: Systems

#1381 Increase RTT/Sysview Stack Size
  CMakeLists.txt
  firmware/cmake/stmlib.cmake
  firmware/third_party/sysview/SEGGER_SYSVIEW_Conf.h
  firmware/third_party/sysview/sysviewFreeRTOSConfigs.h
Labels: Systems

#1321 Inverter Updates Configs
  tools/cascadia_inverter_config/saved_EEPROM_configs/left_inv
  tools/cascadia_inverter_config/saved_EEPROM_configs/right_inv
Labels: VC

#1393 Quintuna VC Bring Up
  firmware/quintuna/CMakeLists.txt
  firmware/quintuna/VC/CMakeLists.txt
  firmware/quintuna/VC/boot/bootloaderConfig.h
  firmware/quintuna/VC/boot/cubemx/Inc/main.h
  firmware/quintuna/VC/boot/cubemx/Inc/stm32h7xx_hal_conf.h
  firmware/quintuna/VC/boot/cubemx/Inc/stm32h7xx_it.h
  firmware/quintuna/VC/boot/cubemx/Src/main.c
  firmware/quintuna/VC/boot/cubemx/Src/stm32h7xx_hal_msp.c
  firmware/quintuna/VC/boot/cubemx/Src/stm32h7xx_it.c
  firmware/quintuna/VC/boot/cubemx/Src/syscalls.c
  firmware/quintuna/VC/boot/cubemx/Src/system_stm32h7xx.c
  firmware/quintuna/VC/boot/cubemx/VC_boot.ioc
  firmware/quintuna/VC/src/cubemx/Inc/FreeRTOSConfig.h
  firmware/quintuna/VC/src/cubemx/Inc/main.h
  firmware/quintuna/VC/src/cubemx/Inc/stm32h7xx_hal_conf.h
  firmware/quintuna/VC/src/cubemx/Inc/stm32h7xx_it.h
  firmware/quintuna/VC/src/cubemx/Src/freertos.c
  firmware/quintuna/VC/src/cubemx/Src/main.c
  firmware/quintuna/VC/src/cubemx/Src/stm32h7xx_hal_msp.c
  firmware/quintuna/VC/src/cubemx/Src/stm32h7xx_it.c
  firmware/quintuna/VC/src/cubemx/Src/syscalls.c
  firmware/quintuna/VC/src/cubemx/Src/system_stm32h7xx.c
  firmware/quintuna/VC/src/cubemx/VC.ioc
  firmware/quintuna/VC/src/cubemx/VC.ioc.md5
  firmware/quintuna/VC/src/tasks.cpp
  firmware/quintuna/VC/src/tasks.h
Labels: VC

#1352 Fix GPS watchdog and get data
  can_bus/quadruna/VC/VC_alerts.json
  can_bus/quadruna/VC/VC_enum.json
  can_bus/quadruna/VC/VC_tx.json
  firmware/quadruna/VC/src/app/app_sbgEllipse.c
  firmware/quadruna/VC/src/app/app_sbgEllipse.h
  firmware/quadruna/VC/src/app/states/app_allStates.c
  firmware/quadruna/VC/src/app/states/app_driveState.c
  firmware/quadruna/VC/src/io/io_sbgEllipse.c
  firmware/quadruna/VC/src/io/io_sbgEllipse.h
  firmware/quadruna/VC/src/tasks.c
  firmware/quadruna/VC/test/test_vcBaseStateMachineTest.h
  firmware/shared/src/app/app_units.h
  firmware/shared/src/app/app_utils.h
Labels: Vehicle Controls
