Repository UBCFormulaElectric/Consolidated-Firmware, pull requests merged in 2025-03, with the labels that each got.

#1452 Async SPI driver
  firmware/quadruna/BMS/CMakeLists.txt
  firmware/quadruna/BMS/src/cubemx/BMS.ioc
  firmware/quadruna/BMS/src/cubemx/BMS.ioc.md5
  firmware/quadruna/BMS/src/cubemx/Inc/stm32h7xx_it.h
  firmware/quadruna/BMS/src/cubemx/Src/stm32h7xx_hal_msp.c
  firmware/quadruna/BMS/src/cubemx/Src/stm32h7xx_it.c
  firmware/quadruna/BMS/src/hw/hw_spis.c
  firmware/quadruna/BMS/src/hw/hw_spis.h
  firmware/quadruna/BMS/src/io/ltc6813/io_ltc6813CellTemps.c
  firmware/quadruna/BMS/src/io/ltc6813/io_ltc6813CellVoltages.c
  firmware/quadruna/BMS/src/io/ltc6813/io_ltc6813Shared.c
  firmware/quadruna/BMS/src/io/ltc6813/io_ltc6813Shared.h
  firmware/quadruna/BMS/src/tasks.c
  firmware/quadruna/VC/CMakeLists.txt
  firmware/quadruna/VC/src/app/app_pumpControl.c
  firmware/quadruna/VC/src/hw/hw_i2cs.c
  firmware/quadruna/VC/src/hw/hw_i2cs.h
  firmware/quadruna/VC/src/io/io_i2cPotentiometer.c
  firmware/quadruna/VC/src/io/io_imu.c
  firmware/quadruna/VC/src/io/io_potentiometer.c
  firmware/quadruna/VC/src/io/io_potentiometer.h
  firmware/shared/src/hw/hw_i2c.c
  firmware/shared/src/hw/hw_i2c.h
  firmware/shared/src/hw/hw_spi.c
  firmware/shared/src/hw/hw_spi.h
  firmware/shared/src/hw/hw_uart.h
Labels: Drivers

#1468 CRIT HW
  firmware/quintuna/CRIT/CMakeLists.txt
  firmware/quintuna/CRIT/src/app/app_heartbeatMonitors.c
  firmware/quintuna/CRIT/src/app/app_heartbeatMonitors.h
  firmware/quintuna/CRIT/src/cubemx/CRIT.ioc
  firmware/quintuna/CRIT/src/cubemx/CRIT.ioc.md5
  firmware/quintuna/CRIT/src/cubemx/Inc/main.h
  firmware/quintuna/CRIT/src/cubemx/Inc/stm32f4xx_it.h
  firmware/quintuna/CRIT/src/cubemx/Src/freertos.c
  firmware/quintuna/CRIT/src/cubemx/Src/main.c
  firmware/quintuna/CRIT/src/cubemx/Src/stm32f4xx_hal_msp.c
  firmware/quintuna/CRIT/src/cubemx/Src/stm32f4xx_hal_timebase_tim.c
  firmware/quintuna/CRIT/src/cubemx/Src/stm32f4xx_it.c
  firmware/quintuna/CRIT/src/cubemx/Src/syscalls.c
  firmware/quintuna/CRIT/src/cubemx/Src/usbd_conf.c
  firmware/quintuna/CRIT/src/hw/hw_cans.c
  firmware/quintuna/CRIT/src/hw/hw_gpios.c
  firmware/quintuna/CRIT/src/hw/hw_gpios.h
  firmware/quintuna/CRIT/src/hw/hw_pwms.c
  firmware/quintuna/CRIT/src/hw/hw_pwms.h
  firmware/quintuna/CRIT/src/hw/hw_spis.c
  firmware/quintuna/CRIT/src/hw/hw_spis.h
  firmware/quintuna/CRIT/src/jobs.c
  firmware/quintuna/CRIT/src/tasks.c
  firmware/shared/src/hw/hw_gpio.c
  firmware/shared/src/hw/hw_gpio.h
  firmware/shared/src/hw/hw_pwmOutput.c
  firmware/shared/src/hw/hw_pwmOutput.h
Labels: DIM [OS]

#1487 Change Submodule Path
  firmware/cmake/dependencies.cmake
Labels: Build System/DevEx

#1489 Revert MessageStreams
  firmware/shared/src/io/io_canLoggingQueue.c
  firmware/shared/src/io/io_canQueue.c
Labels: Systems

#1367 BMS Diagnostics Mode
  can_bus/quadruna/BMS/BMS_tx.json
  can_bus/quadruna/Debug/Debug_enum.json
  firmware/quadruna/BMS/src/app/app_accumulator.h
  firmware/quadruna/BMS/src/app/app_diagnosticsMode.c
  firmware/quadruna/BMS/src/app/app_diagnosticsMode.h
  firmware/quadruna/BMS/src/app/states/app_allStates.c
  firmware/quadruna/BMS/src/io/ltc6813/io_ltc6813CellTemps.c
  firmware/quadruna/BMS/src/io/ltc6813/io_ltc6813CellTemps.h
  firmware/quadruna/BMS/test/test_bmsBaseStateMachineTest.h
  firmware/quadruna/BMS/test/test_diagnosticsMode.cpp
Labels: BMS

#1503 Fix CheckConnection USB behaviour - trigger Chimera on Every Loop of 100Hz task.
  firmware/chimera_v2/README.md
  firmware/chimera_v2/examples/crit_blinky.py
  firmware/dev/SSM/src/cubemx/SSM.ioc
  firmware/dev/SSM/src/cubemx/SSM.ioc.md5
  firmware/dev/SSM/src/cubemx/Src/main.c
  firmware/dev/SSM/src/cubemx/Src/usbd_desc.c
  firmware/dev/f4dev/src/cubemx/Src/main.c
  firmware/quintuna/CRIT/src/cubemx/Src/usbd_cdc_if.c
  firmware/quintuna/CRIT/src/tasks.c
  firmware/shared/src/hw/hw_usb.c
  firmware/shared/src/hw/hw_usb.h
  firmware/shared/src/io/io_chimera_v2.c
  firmware/shared/src/io/io_chimera_v2.h
Labels: Validation

#1443 FSM HW bring up
  Pipfile
  Pipfile.lock
  can_bus/quintuna/FSM/FSM_rx.json
  can_bus/quintuna/FSM/FSM_tx.json
  can_bus/quintuna/VC/VC_tx.json
  firmware/chimera_v2/chimera_v2.py
  firmware/chimera_v2/proto/CMakeLists.txt
  firmware/chimera_v2/proto/fsm.proto
  firmware/chimera_v2/proto/shared.proto
  firmware/chimera_v2/proto_autogen/crit_pb2.py
  firmware/chimera_v2/proto_autogen/f4dev_pb2.py
  firmware/chimera_v2/proto_autogen/fsm_pb2.py
  firmware/chimera_v2/proto_autogen/fsm_pb2.pyi
  firmware/chimera_v2/proto_autogen/nanopb_pb2.py
  firmware/chimera_v2/proto_autogen/shared_pb2.py
  firmware/chimera_v2/proto_autogen/shared_pb2.pyi
  firmware/chimera_v2/proto_autogen/ssm_pb2.py
  firmware/quintuna/FSM/CMakeLists.txt
  firmware/quintuna/FSM/boot/cubemx/Src/main.c
  firmware/quintuna/FSM/src/cubemx/FSM.ioc
  firmware/quintuna/FSM/src/cubemx/FSM.ioc.md5
  firmware/quintuna/FSM/src/cubemx/Inc/FreeRTOSConfig.h
  firmware/quintuna/FSM/src/cubemx/Inc/main.h
  firmware/quintuna/FSM/src/cubemx/Inc/stm32f4xx_hal_conf.h
  firmware/quintuna/FSM/src/cubemx/Inc/stm32f4xx_it.h
  firmware/quintuna/FSM/src/cubemx/Inc/usb_device.h
  firmware/quintuna/FSM/src/cubemx/Inc/usbd_cdc_if.h
  firmware/quintuna/FSM/src/cubemx/Inc/usbd_conf.h
  firmware/quintuna/FSM/src/cubemx/Inc/usbd_desc.h
  firmware/quintuna/FSM/src/cubemx/Src/main.c
  firmware/quintuna/FSM/src/cubemx/Src/stm32f4xx_hal_msp.c
  firmware/quintuna/FSM/src/cubemx/Src/stm32f4xx_hal_timebase_tim.c
  firmware/quintuna/FSM/src/cubemx/Src/stm32f4xx_it.c
  firmware/quintuna/FSM/src/cubemx/Src/usb_device.c
  firmware/quintuna/FSM/src/cubemx/Src/usbd_cdc_if.c
  firmware/quintuna/FSM/src/cubemx/Src/usbd_conf.c
  firmware/quintuna/FSM/src/cubemx/Src/usbd_desc.c
  firmware/quintuna/FSM/src/hw/hw_adcs.c
  firmware/quintuna/FSM/src/hw/hw_adcs.h
  firmware/quintuna/FSM/src/hw/hw_cans.c
  firmware/quintuna/FSM/src/hw/hw_cans.h
  firmware/quintuna/FSM/src/hw/hw_gpios.c
  firmware/quintuna/FSM/src/hw/hw_gpios.h
  firmware/quintuna/FSM/src/hw/hw_i2cs.c
  firmware/quintuna/FSM/src/hw/hw_i2cs.h
  firmware/quintuna/FSM/src/hw/hw_sysviewDescConfig.c
  firmware/quintuna/FSM/src/io/io_chimeraConfig_v2.c
  firmware/quintuna/FSM/src/io/io_chimeraConfig_v2.h
  firmware/quintuna/FSM/src/jobs.c
  firmware/quintuna/FSM/src/jobs.h
  firmware/quintuna/FSM/src/tasks.c
  firmware/quintuna/FSM/src/tasks.cpp
  firmware/quintuna/FSM/src/tasks.h
  firmware/shared/src/io/io_chimera_v2.c
Labels: FSM/RSM

#1507 Add Scope to Chimera V2
  firmware/chimera_v2/chimera_v2.py
  firmware/chimera_v2/docs/chimera_v2.md
  firmware/chimera_v2/docs/scope.md
  firmware/chimera_v2/pyproject.toml
  firmware/chimera_v2/scope.py
  firmware/chimera_v2/scripts/generate_docs.sh
  firmware/chimera_v2/scripts/lint.sh
Labels: Validation

#1492 Chimera SPI implementation
  .vscode/tasks.json
  firmware/chimera_v2/README.md
  firmware/chimera_v2/chimera_v2.py
  firmware/chimera_v2/docs/chimera_v2.md
  firmware/chimera_v2/examples/crit_7_seg.py
  firmware/chimera_v2/proto/crit.proto
  firmware/chimera_v2/proto/f4dev.proto
  firmware/chimera_v2/proto/fsm.proto
  firmware/chimera_v2/proto/rsm.proto
  firmware/chimera_v2/proto/shared.proto
  firmware/chimera_v2/proto/ssm.proto
  firmware/chimera_v2/proto_autogen/crit_pb2.py
  firmware/chimera_v2/proto_autogen/crit_pb2.pyi
  firmware/chimera_v2/proto_autogen/f4dev_pb2.py
  firmware/chimera_v2/proto_autogen/f4dev_pb2.pyi
  firmware/chimera_v2/proto_autogen/fsm_pb2.py
  firmware/chimera_v2/proto_autogen/fsm_pb2.pyi
  firmware/chimera_v2/proto_autogen/nanopb_pb2.py
  firmware/chimera_v2/proto_autogen/rsm_pb2.py
  firmware/chimera_v2/proto_autogen/rsm_pb2.pyi
  firmware/chimera_v2/proto_autogen/shared_pb2.py
  firmware/chimera_v2/proto_autogen/shared_pb2.pyi
  firmware/chimera_v2/proto_autogen/ssm_pb2.py
  firmware/chimera_v2/proto_autogen/ssm_pb2.pyi
  firmware/dev/SSM/CMakeLists.txt
  firmware/dev/SSM/src/cubemx/Src/main.c
  firmware/dev/SSM/src/hw/hw_spis.c
  firmware/dev/SSM/src/hw/hw_spis.h
  firmware/dev/SSM/src/io/io_chimeraConfig_v2.c
  firmware/dev/SSM/src/io/io_chimeraConfig_v2.h
  firmware/dev/f4dev/CMakeLists.txt
  firmware/dev/f4dev/src/cubemx/Src/main.c
  firmware/dev/f4dev/src/hw/hw_spis.c
  firmware/dev/f4dev/src/hw/hw_spis.h
  firmware/dev/f4dev/src/io/io_chimeraConfig_v2.c
  firmware/dev/f4dev/src/io/io_chimeraConfig_v2.h
  firmware/quintuna/CRIT/CMakeLists.txt
  firmware/quintuna/CRIT/src/io/io_chimeraConfig_v2.c
  firmware/quintuna/CRIT/src/io/io_chimeraConfig_v2.h
  firmware/quintuna/CRIT/src/jobs.c
  firmware/quintuna/CRIT/src/tasks.c
  firmware/quintuna/FSM/CMakeLists.txt
  firmware/quintuna/FSM/src/hw/hw_spis.c
  firmware/quintuna/FSM/src/hw/hw_spis.h
  firmware/quintuna/FSM/src/io/io_chimeraConfig_v2.c
  firmware/quintuna/FSM/src/io/io_chimeraConfig_v2.h
  firmware/quintuna/FSM/src/tasks.c
  firmware/quintuna/RSM/CMakeLists.txt
  firmware/quintuna/RSM/src/hw/hw_spis.c
  firmware/quintuna/RSM/src/hw/hw_spis.h
  firmware/quintuna/RSM/src/io/io_chimeraConfig_v2.c
  firmware/quintuna/RSM/src/io/io_chimeraConfig_v2.h
  firmware/quintuna/RSM/src/tasks.c
  firmware/shared/src/io/io_chimera_v2.c
  firmware/shared/src/io/io_chimera_v2.h
Labels: Validation

#1470 dam hw layer
  .vscode/launch.json
  firmware/chimera/proto/CMakeLists.txt
  firmware/chimera/proto/DAM.proto
  firmware/chimera/proto/shared.proto
  firmware/chimera_v2/chimera_v2.py
  firmware/chimera_v2/docs/chimera_v2.md
  firmware/chimera_v2/examples/dam_blinky.py
  firmware/chimera_v2/proto/CMakeLists.txt
  firmware/chimera_v2/proto/dam.proto
  firmware/chimera_v2/proto/shared.proto
  firmware/chimera_v2/proto_autogen/dam_pb2.py
  firmware/chimera_v2/proto_autogen/dam_pb2.pyi
  firmware/chimera_v2/proto_autogen/shared_pb2.py
  firmware/chimera_v2/proto_autogen/shared_pb2.pyi
  firmware/dev/SSM/src/cubemx/SSM.ioc
  firmware/quadruna/VC/boot/cubemx/Inc/main.h
  firmware/quadruna/VC/src/hw/hw_uarts.c
  firmware/quintuna/DAM/CMakeLists.txt
  firmware/quintuna/DAM/src/cubemx/DAM.ioc
  firmware/quintuna/DAM/src/cubemx/DAM.ioc.md5
  firmware/quintuna/DAM/src/cubemx/Inc/main.h
  firmware/quintuna/DAM/src/cubemx/Inc/stm32h7xx_hal_conf.h
  firmware/quintuna/DAM/src/cubemx/Src/main.c
  firmware/quintuna/DAM/src/cubemx/Src/stm32h7xx_it.c
  firmware/quintuna/DAM/src/cubemx/Src/usbd_cdc_if.c
  firmware/quintuna/DAM/src/cubemx/Src/usbd_conf.c
  firmware/quintuna/DAM/src/cubemx/Src/usbd_desc.c
  firmware/quintuna/DAM/src/hw/hw_adcs.c
  firmware/quintuna/DAM/src/hw/hw_adcs.h
  firmware/quintuna/DAM/src/hw/hw_cans.c
  firmware/quintuna/DAM/src/hw/hw_cans.h
  firmware/quintuna/DAM/src/hw/hw_gpios.c
  firmware/quintuna/DAM/src/hw/hw_gpios.h
  firmware/quintuna/DAM/src/hw/hw_i2cs.c
  firmware/quintuna/DAM/src/hw/hw_i2cs.h
  firmware/quintuna/DAM/src/hw/hw_sds.c
  firmware/quintuna/DAM/src/hw/hw_spis.c
  firmware/quintuna/DAM/src/hw/hw_spis.h
  firmware/quintuna/DAM/src/hw/hw_sysviewDescConfig.c
  firmware/quintuna/DAM/src/hw/hw_uarts.c
  firmware/quintuna/DAM/src/hw/hw_uarts.h
  firmware/quintuna/DAM/src/hw/hw_watchdogConfig.c
  firmware/quintuna/DAM/src/hw/hw_watchdogConfig.h
  firmware/quintuna/DAM/src/io/io_chimeraConfig_v2.c
  firmware/quintuna/DAM/src/io/io_chimeraConfig_v2.h
  firmware/quintuna/DAM/src/jobs.c
  firmware/quintuna/DAM/src/jobs.h
  firmware/quintuna/DAM/src/tasks.c
  firmware/quintuna/DAM/src/tasks.h
  firmware/quintuna/VC/boot/cubemx/Inc/main.h
  firmware/shared/src/hw/hw_gpio.c
  firmware/shared/src/hw/hw_gpio.h
  firmware/shared/src/io/io_chimera_v2.c
Labels: Telem/DAM

#1516 Use Feature Flags to Remove Unused Chimera V2 Peripherals
  firmware/chimera_v2/README.md
  firmware/chimera_v2/chimera_v2.py
  firmware/chimera_v2/docs/chimera_v2.md
  firmware/chimera_v2/proto/dam.proto
  firmware/chimera_v2/proto/f4dev.proto
  firmware/chimera_v2/proto/fsm.proto
  firmware/chimera_v2/proto/rsm.proto
  firmware/chimera_v2/proto/shared.proto
  firmware/chimera_v2/proto/ssm.proto
  firmware/chimera_v2/proto_autogen/dam_pb2.py
  firmware/chimera_v2/proto_autogen/dam_pb2.pyi
  firmware/chimera_v2/proto_autogen/f4dev_pb2.py
  firmware/chimera_v2/proto_autogen/f4dev_pb2.pyi
  firmware/chimera_v2/proto_autogen/fsm_pb2.py
  firmware/chimera_v2/proto_autogen/fsm_pb2.pyi
  firmware/chimera_v2/proto_autogen/rsm_pb2.py
  firmware/chimera_v2/proto_autogen/rsm_pb2.pyi
  firmware/chimera_v2/proto_autogen/shared_pb2.py
  firmware/chimera_v2/proto_autogen/shared_pb2.pyi
  firmware/chimera_v2/proto_autogen/ssm_pb2.py
  firmware/chimera_v2/proto_autogen/ssm_pb2.pyi
  firmware/dev/SSM/CMakeLists.txt
  firmware/dev/SSM/src/cubemx/Src/main.c
  firmware/dev/SSM/src/hw/hw_adcs.c
  firmware/dev/SSM/src/hw/hw_adcs.h
  firmware/dev/SSM/src/hw/hw_i2cs.c
  firmware/dev/SSM/src/hw/hw_i2cs.h
  firmware/dev/SSM/src/io/io_chimeraConfig_v2.c
  firmware/dev/SSM/src/io/io_chimeraConfig_v2.h
  firmware/dev/f4dev/src/cubemx/Src/main.c
  firmware/dev/f4dev/src/io/io_chimeraConfig_v2.c
  firmware/dev/f4dev/src/io/io_chimeraConfig_v2.h
  firmware/quintuna/CRIT/CMakeLists.txt
  firmware/quintuna/CRIT/src/io/io_chimeraConfig_v2.c
  firmware/quintuna/CRIT/src/io/io_chimeraConfig_v2.h
  firmware/quintuna/CRIT/src/tasks.c
  firmware/quintuna/DAM/CMakeLists.txt
  firmware/quintuna/DAM/src/hw/hw_adcs.c
  firmware/quintuna/DAM/src/hw/hw_adcs.h
  firmware/quintuna/DAM/src/hw/hw_spis.c
  firmware/quintuna/DAM/src/hw/hw_spis.h
  firmware/quintuna/DAM/src/io/io_chimeraConfig_v2.c
  firmware/quintuna/DAM/src/io/io_chimeraConfig_v2.h
  firmware/quintuna/DAM/src/tasks.c
  firmware/quintuna/FSM/CMakeLists.txt
  firmware/quintuna/FSM/src/hw/hw_spis.c
  firmware/quintuna/FSM/src/hw/hw_spis.h
  firmware/quintuna/FSM/src/io/io_chimeraConfig_v2.c
  firmware/quintuna/FSM/src/io/io_chimeraConfig_v2.h
  firmware/quintuna/FSM/src/tasks.c
  firmware/quintuna/RSM/CMakeLists.txt
  firmware/quintuna/RSM/src/hw/hw_spis.c
  firmware/quintuna/RSM/src/hw/hw_spis.h
  firmware/quintuna/RSM/src/io/io_chimeraConfig_v2.c
  firmware/quintuna/RSM/src/io/io_chimeraConfig_v2.h
  firmware/quintuna/RSM/src/tasks.c
  firmware/shared/src/io/io_chimera_v2.c
  firmware/shared/src/io/io_chimera_v2.h
Labels: Validation

#1508 Fix CAN logging bugs
  firmware/dev/h7dev/CMakeLists.txt
  firmware/dev/h7dev/src/cubemx/Src/main.c
  firmware/quadruna/VC/CMakeLists.txt
  firmware/quadruna/VC/src/app/states/app_allStates.c
  firmware/quadruna/VC/src/jobs.c
  firmware/quadruna/VC/src/tasks.c
  firmware/quintuna/DAM/src/tasks.c
  firmware/shared/src/hw/hw_sd.c
  firmware/shared/src/hw/hw_sd.h
  firmware/shared/src/io/io_canLogging.c
  firmware/shared/src/io/io_canLogging.h
  firmware/shared/src/io/io_canLoggingQueue.c
  firmware/shared/src/io/io_fileSystem.h
  firmware/shared/src/io/io_fileSystem_logfs.c
  firmware/shared/src/io/io_jsoncan.c
  firmware/shared/src/io/io_log.h
Labels: Telem/DAM

#1469 BMS Quintuna hw layer
  .vscode/launch.json
  firmware/chimera_v2/chimera_v2.py
  firmware/chimera_v2/docs/chimera_v2.md
  firmware/chimera_v2/proto/CMakeLists.txt
  firmware/chimera_v2/proto/bms.proto
  firmware/chimera_v2/proto/crit.proto
  firmware/chimera_v2/proto/shared.proto
  firmware/chimera_v2/proto_autogen/bms_pb2.py
  firmware/chimera_v2/proto_autogen/bms_pb2.pyi
  firmware/chimera_v2/proto_autogen/crit_pb2.py
  firmware/chimera_v2/proto_autogen/crit_pb2.pyi
  firmware/chimera_v2/proto_autogen/shared_pb2.py
  firmware/chimera_v2/proto_autogen/shared_pb2.pyi
  firmware/quadruna/BMS/src/hw/hw_spis.c
  firmware/quintuna/BMS/CMakeLists.txt
  firmware/quintuna/BMS/boot/cubemx/Src/main.c
  firmware/quintuna/BMS/src/cubemx/BMS.ioc
  firmware/quintuna/BMS/src/cubemx/BMS.ioc.md5
  firmware/quintuna/BMS/src/cubemx/Inc/main.h
  firmware/quintuna/BMS/src/cubemx/Inc/stm32h7xx_hal_conf.h
  firmware/quintuna/BMS/src/cubemx/Inc/stm32h7xx_it.h
  firmware/quintuna/BMS/src/cubemx/Inc/usb_device.h
  firmware/quintuna/BMS/src/cubemx/Inc/usbd_cdc_if.h
  firmware/quintuna/BMS/src/cubemx/Inc/usbd_conf.h
  firmware/quintuna/BMS/src/cubemx/Inc/usbd_desc.h
  firmware/quintuna/BMS/src/cubemx/Src/main.c
  firmware/quintuna/BMS/src/cubemx/Src/stm32h7xx_hal_msp.c
  firmware/quintuna/BMS/src/cubemx/Src/stm32h7xx_it.c
  firmware/quintuna/BMS/src/cubemx/Src/usb_device.c
  firmware/quintuna/BMS/src/cubemx/Src/usbd_cdc_if.c
  firmware/quintuna/BMS/src/cubemx/Src/usbd_conf.c
  firmware/quintuna/BMS/src/cubemx/Src/usbd_desc.c
  firmware/quintuna/BMS/src/hw/hw_adcs.c
  firmware/quintuna/BMS/src/hw/hw_adcs.h
  firmware/quintuna/BMS/src/hw/hw_cans.c
  firmware/quintuna/BMS/src/hw/hw_cans.h
  firmware/quintuna/BMS/src/hw/hw_gpios.c
  firmware/quintuna/BMS/src/hw/hw_gpios.h
  firmware/quintuna/BMS/src/hw/hw_i2cs.c
  firmware/quintuna/BMS/src/hw/hw_pwms.c
  firmware/quintuna/BMS/src/hw/hw_pwms.h
  firmware/quintuna/BMS/src/hw/hw_sds.c
  firmware/quintuna/BMS/src/hw/hw_spis.c
  firmware/quintuna/BMS/src/hw/hw_spis.h
  firmware/quintuna/BMS/src/hw/hw_sysviewDescConfig.c
  firmware/quintuna/BMS/src/hw/hw_watchdogConfig.c
  firmware/quintuna/BMS/src/hw/hw_watchdogConfig.h
  firmware/quintuna/BMS/src/io/io_chimeraConfig_v2.c
  firmware/quintuna/BMS/src/io/io_chimeraConfig_v2.h
  firmware/quintuna/BMS/src/tasks.c
  firmware/quintuna/BMS/src/tasks.h
  firmware/quintuna/CRIT/src/hw/hw_gpios.c
  firmware/quintuna/CRIT/src/hw/hw_gpios.h
  firmware/quintuna/CRIT/src/hw/hw_spis.c
  firmware/shared/src/hw/hw_spi.c
  firmware/shared/src/hw/hw_spi.h
  firmware/shared/src/io/io_chimera_v2.c
Labels: BMS, Validation

#1504 Tv rework
  can_bus/quadruna/VC/VC_tx.json
  firmware/quadruna/VC/CMakeLists.txt
  firmware/quadruna/VC/src/app/app_imu.c
  firmware/quadruna/VC/src/app/app_imu.h
  firmware/quadruna/VC/src/app/app_sbgEllipse.c
  firmware/quadruna/VC/src/app/app_sbgEllipse.h
  firmware/quadruna/VC/src/app/states/app_allStates.c
  firmware/quadruna/VC/src/app/vehicle_dynamics/app_loadTransfer.c
  firmware/quadruna/VC/src/app/vehicle_dynamics/app_loadTransfer.h
  firmware/quadruna/VC/src/app/vehicle_dynamics/app_torqueVectoring.c
  firmware/quadruna/VC/src/app/vehicle_dynamics/app_vehicleDynamics.h
  firmware/quadruna/VC/src/app/vehicle_dynamics/app_vehicleDynamicsConstants.c
  firmware/quadruna/VC/src/app/vehicle_dynamics/app_vehicleDynamicsConstants.h
  firmware/quadruna/VC/src/app/vehicle_dynamics/app_yawRateController.c
  firmware/quadruna/VC/src/app/vehicle_dynamics/app_yawRateController.h
  firmware/quadruna/VC/src/hw/hw_i2cs.c
  firmware/quadruna/VC/src/io/io_imu_config.c
  firmware/quadruna/VC/src/io/io_imu_config.h
  firmware/quadruna/VC/src/jobs.c
  firmware/quadruna/VC/test/test_loadTransfer.cpp
  firmware/quadruna/VC/test/vehicle_dynamics/test_yawRateController.cpp
  firmware/shared/src/app/app_units.h
  firmware/shared/src/io/io_imu.c
  firmware/shared/src/io/io_imu.h
  software/yaw_rate_controller/YawRateController.slx
Labels: Vehicle Controls

#1526 FSM ADC Hotfix
  firmware/quintuna/FSM/src/cubemx/FSM.ioc
  firmware/quintuna/FSM/src/cubemx/FSM.ioc.md5
  firmware/quintuna/FSM/src/cubemx/Inc/main.h
  firmware/quintuna/FSM/src/cubemx/Src/main.c
  firmware/quintuna/FSM/src/cubemx/Src/stm32f4xx_hal_msp.c
  firmware/quintuna/FSM/src/cubemx/Src/stm32f4xx_it.c
  firmware/quintuna/FSM/src/tasks.c
  firmware/shared/src/io/io_chimera_v2.c
Labels: FSM/RSM

#1528 Move to CRIT SPIs to Open Drain
  firmware/chimera_v2/proto/crit.proto
  firmware/chimera_v2/proto/shared.proto
  firmware/chimera_v2/proto_autogen/crit_pb2.py
  firmware/chimera_v2/proto_autogen/crit_pb2.pyi
  firmware/chimera_v2/proto_autogen/shared_pb2.py
  firmware/chimera_v2/proto_autogen/shared_pb2.pyi
  firmware/quintuna/CRIT/CMakeLists.txt
  firmware/quintuna/CRIT/src/cubemx/CRIT.ioc
  firmware/quintuna/CRIT/src/cubemx/CRIT.ioc.md5
  firmware/quintuna/CRIT/src/cubemx/Inc/main.h
  firmware/quintuna/CRIT/src/cubemx/Inc/stm32f4xx_hal_conf.h
  firmware/quintuna/CRIT/src/cubemx/Inc/stm32f4xx_it.h
  firmware/quintuna/CRIT/src/cubemx/Src/main.c
  firmware/quintuna/CRIT/src/cubemx/Src/stm32f4xx_hal_msp.c
  firmware/quintuna/CRIT/src/cubemx/Src/stm32f4xx_it.c
  firmware/quintuna/CRIT/src/hw/hw_gpios.c
  firmware/quintuna/CRIT/src/hw/hw_gpios.h
  firmware/quintuna/CRIT/src/hw/hw_spis.c
  firmware/quintuna/CRIT/src/hw/hw_spis.h
  firmware/quintuna/CRIT/src/io/io_chimeraConfig_v2.c
  firmware/shared/src/io/io_chimera_v2.c
Labels: Validation

#1530 SSM Chimera Setup / HW Layer
  firmware/chimera_v2/proto/shared.proto
  firmware/chimera_v2/proto/ssm.proto
  firmware/chimera_v2/proto_autogen/shared_pb2.py
  firmware/chimera_v2/proto_autogen/shared_pb2.pyi
  firmware/chimera_v2/proto_autogen/ssm_pb2.py
  firmware/chimera_v2/proto_autogen/ssm_pb2.pyi
  firmware/dev/SSM/src/cubemx/Inc/main.h
  firmware/dev/SSM/src/cubemx/SSM.ioc
  firmware/dev/SSM/src/cubemx/SSM.ioc.md5
  firmware/dev/SSM/src/cubemx/Src/main.c
  firmware/dev/SSM/src/hw/hw_gpios.c
  firmware/dev/SSM/src/hw/hw_gpios.h
  firmware/dev/SSM/src/hw/hw_spis.c
  firmware/dev/SSM/src/hw/hw_spis.h
  firmware/dev/SSM/src/io/io_chimeraConfig_v2.c
  firmware/shared/src/io/io_chimera_v2.c
Labels: Validation

#1427 VC HW/IO bringup
  .vscode/tasks.json
  firmware/chimera_v2/chimera_v2.py
  firmware/chimera_v2/proto/CMakeLists.txt
  firmware/chimera_v2/proto/shared.proto
  firmware/chimera_v2/proto/vc.proto
  firmware/quintuna/CMakeLists.txt
  firmware/quintuna/VC/CMakeLists.txt
  firmware/quintuna/VC/src/cubemx/Inc/FreeRTOSConfig.h
  firmware/quintuna/VC/src/cubemx/Inc/main.h
  firmware/quintuna/VC/src/cubemx/Inc/stm32h7xx_hal_conf.h
  firmware/quintuna/VC/src/cubemx/Inc/stm32h7xx_it.h
  firmware/quintuna/VC/src/cubemx/Inc/usb_device.h
  firmware/quintuna/VC/src/cubemx/Inc/usbd_cdc_if.h
  firmware/quintuna/VC/src/cubemx/Inc/usbd_conf.h
  firmware/quintuna/VC/src/cubemx/Inc/usbd_desc.h
  firmware/quintuna/VC/src/cubemx/Src/main.c
  firmware/quintuna/VC/src/cubemx/Src/stm32h7xx_hal_msp.c
  firmware/quintuna/VC/src/cubemx/Src/stm32h7xx_hal_timebase_tim.c
  firmware/quintuna/VC/src/cubemx/Src/stm32h7xx_it.c
  firmware/quintuna/VC/src/cubemx/Src/usb_device.c
  firmware/quintuna/VC/src/cubemx/Src/usbd_cdc_if.c
  firmware/quintuna/VC/src/cubemx/Src/usbd_conf.c
  firmware/quintuna/VC/src/cubemx/Src/usbd_desc.c
  firmware/quintuna/VC/src/cubemx/VC.ioc
  firmware/quintuna/VC/src/cubemx/VC.ioc.md5
  firmware/quintuna/VC/src/hw/hw_adcs.c
  firmware/quintuna/VC/src/hw/hw_adcs.h
  firmware/quintuna/VC/src/hw/hw_cans.c
  firmware/quintuna/VC/src/hw/hw_cans.h
  firmware/quintuna/VC/src/hw/hw_gpios.c
  firmware/quintuna/VC/src/hw/hw_gpios.h
  firmware/quintuna/VC/src/hw/hw_i2cs.c
  firmware/quintuna/VC/src/hw/hw_i2cs.h
  firmware/quintuna/VC/src/hw/hw_sysviewDescConfig.c
  firmware/quintuna/VC/src/hw/hw_uarts.c
  firmware/quintuna/VC/src/hw/hw_uarts.h
  firmware/quintuna/VC/src/jobs.c
  firmware/quintuna/VC/src/jobs.h
  firmware/quintuna/VC/src/tasks.c
  firmware/quintuna/VC/src/tasks.h
  firmware/shared/src/hw/hw_can.h
Labels: VC

#1534 Add SVDs for Debugging
  tools/svd/STM32F412.svd
  tools/svd/STM32H733.svd
Labels: Build System/DevEx

#1538 Reset reason driver
  firmware/shared/src/hw/hw_bootup.h
  firmware/shared/src/hw/hw_resetReason.c
  firmware/shared/src/hw/hw_resetReason.h
Labels: Systems

#1524 Ashkan/shutdown loop io and buzzer
  firmware/cmake/dependencies.cmake
  firmware/quintuna/DAM/src/cubemx/Src/usbd_conf.c
  firmware/quintuna/DAM/src/io/io_buzzer.c
  firmware/quintuna/DAM/src/io/io_buzzer.h
  firmware/quintuna/DAM/src/io/io_shdn_loop.c
  firmware/quintuna/DAM/src/io/io_shdn_loop.h
  firmware/quintuna/DAM/src/io/io_tsim.h
  firmware/quintuna/DAM/src/tasks.c
Labels: Telem/DAM

#1540 Bms/ts spelling fix
  firmware/quadruna/BMS/src/app/app_tractiveSystem.c
  firmware/quadruna/BMS/src/app/app_tractiveSystem.h
  firmware/quadruna/BMS/src/app/states/app_allStates.c
  firmware/quadruna/BMS/src/app/states/app_faultState.c
  firmware/quadruna/BMS/src/cubemx/BMS.ioc
  firmware/quadruna/BMS/src/cubemx/BMS.ioc.md5
  firmware/quadruna/BMS/src/cubemx/Src/main.c
Labels: BMS
