Repository UBCFormulaElectric/Consolidated-Firmware, pull requests merged in 2025-02, with the labels that each got.

#1439 Specify Pipenv Path via. CMake Variable
  python.cmake
Labels: Build System/DevEx

#1444 Task Monitor Hotfix
  firmware/shared/src/io/io_taskMonitor.c
  firmware/shared/src/io/io_taskMonitor.h
Labels: Drivers

#1445 IMU Hotfix
  can_bus/quadruna/VC/VC_tx.json
  firmware/quadruna/VC/src/hw/hw_i2cs.c
  firmware/quadruna/VC/src/hw/hw_i2cs.h
  firmware/quadruna/VC/src/io/io_imu.c
  firmware/shared/src/hw/hw_i2c.c
  firmware/shared/src/hw/hw_i2c.h
Labels: Drivers

#1440 Async I2C driver
  firmware/quadruna/VC/src/cubemx/Inc/main.h
  firmware/quadruna/VC/src/cubemx/Inc/stm32h7xx_it.h
  firmware/quadruna/VC/src/cubemx/Src/stm32h7xx_hal_msp.c
  firmware/quadruna/VC/src/cubemx/Src/stm32h7xx_it.c
  firmware/quadruna/VC/src/cubemx/VC.ioc
  firmware/quadruna/VC/src/cubemx/VC.ioc.md5
  firmware/quadruna/VC/src/hw/hw_i2cs.c
  firmware/quadruna/VC/src/hw/hw_i2cs.h
  firmware/quadruna/VC/src/io/io_i2cPotentiometer.c
  firmware/quadruna/VC/src/io/io_imu.c
  firmware/shared/src/hw/hw_i2c.c
  firmware/shared/src/hw/hw_i2c.h
Labels: Drivers

#1432 Cortex-M7 compiler flag fix
  firmware/cmake/embedded.cmake
  firmware/cmake/stmlib.cmake
Labels: Drivers

#1457 SBG Error Codes to CAN
  can_bus/quadruna/VC/VC_enum.json
  can_bus/quadruna/VC/VC_tx.json
  firmware/quadruna/VC/src/io/io_sbgEllipse.c
Labels: Vehicle Controls

#1462 Pyproject for JSONCAN
  scripts/code_generation/jsoncan/pyproject.toml
Labels: Web

#1450 Switch can queue from message queue to message buffer
  can_bus/quadruna/BRUSA/BRUSA_tx.json
  firmware/shared/src/hw/hw_sd.c
  firmware/shared/src/io/io_canLoggingQueue.c
  firmware/shared/src/io/io_canQueue.c
  firmware/shared/src/io/io_fileSystem_logfs.c
Labels: Drivers
